#!/bin/bash
# Generate STATUS.md from .beads/issues.jsonl
# Usage: ./scripts/generate-status.sh

set -e

BEADS_DIR=".beads"
ISSUES_FILE="$BEADS_DIR/issues.jsonl"
STATUS_FILE="$BEADS_DIR/status.json"
OUTPUT_FILE="STATUS.md"

if [ ! -f "$ISSUES_FILE" ]; then
  echo "❌ No issues file found: $ISSUES_FILE"
  exit 1
fi

# Generate status JSON first
./scripts/bd.sh status > /dev/null 2>&1 || true

# Read status
if [ -f "$STATUS_FILE" ]; then
  current_epic=$(jq -r '.current_epic // "none"' "$STATUS_FILE")
  active_issues=$(jq -r '.active_issues[]?' "$STATUS_FILE" | tr '\n' ' ')
  completed_today=$(jq -r '.completed_today[]?' "$STATUS_FILE" | tr '\n' ' ')
  next_ready=$(jq -r '.next_ready[]?' "$STATUS_FILE" | head -5 | tr '\n' ' ')
  blocked_count=$(jq -r '.blocked_count // 0' "$STATUS_FILE")
else
  current_epic="none"
  active_issues=""
  completed_today=""
  next_ready=""
  blocked_count=0
fi

# Generate STATUS.md
cat > "$OUTPUT_FILE" << EOF
# 📊 STATUS - Current Project State

**Last Updated:** $(date -u +"%Y-%m-%dT%H:%M:%SZ")  
**Generated by:** \`./scripts/generate-status.sh\`

---

## 🔥 RIGHT NOW

**Current Epic:** $current_epic

**Active Issues:**
EOF

if [ -n "$active_issues" ]; then
  for id in $active_issues; do
    issue=$(grep "\"id\":\"$id\"" "$ISSUES_FILE" | head -1)
    if [ -n "$issue" ]; then
      title=$(echo "$issue" | jq -r '.title')
      estimated=$(echo "$issue" | jq -r '.estimated_time // "?"')
      echo "- **$id**: $title (est: $estimated)" >> "$OUTPUT_FILE"
    fi
  done
else
  echo "- No active issues" >> "$OUTPUT_FILE"
fi

cat >> "$OUTPUT_FILE" << EOF

---

## ✅ COMPLETED TODAY

EOF

if [ -n "$completed_today" ]; then
  for id in $completed_today; do
    issue=$(grep "\"id\":\"$id\"" "$ISSUES_FILE" | head -1)
    if [ -n "$issue" ]; then
      title=$(echo "$issue" | jq -r '.title')
      echo "- **$id**: $title" >> "$OUTPUT_FILE"
    fi
  done
else
  echo "- No issues completed today" >> "$OUTPUT_FILE"
fi

cat >> "$OUTPUT_FILE" << EOF

---

## 🎯 NEXT SESSION

**Ready to start:**
EOF

if [ -n "$next_ready" ]; then
  count=1
  for id in $next_ready; do
    issue=$(grep "\"id\":\"$id\"" "$ISSUES_FILE" | head -1)
    if [ -n "$issue" ]; then
      title=$(echo "$issue" | jq -r '.title')
      priority=$(echo "$issue" | jq -r '.priority // 1')
      estimated=$(echo "$issue" | jq -r '.estimated_time // "?"')
      echo "$count. **$id**: $title (priority: $priority, est: $estimated)" >> "$OUTPUT_FILE"
      count=$((count + 1))
    fi
  done
else
  echo "1. No ready issues" >> "$OUTPUT_FILE"
fi

cat >> "$OUTPUT_FILE" << EOF

---

## 📈 STATISTICS

**Blocked Issues:** $blocked_count

**Quick Commands:**
\`\`\`bash
# See ready issues
./scripts/bd.sh ready

# Start working on issue
./scripts/bd.sh start {issue-id}

# Complete issue
./scripts/bd.sh complete {issue-id}

# Discover new issue
./scripts/bd.sh discover "Description" --from {issue-id}

# Update status
./scripts/generate-status.sh
\`\`\`

---

**Note:** This file is auto-generated. To update, run \`./scripts/generate-status.sh\`

EOF

echo "✅ STATUS.md generated"

