Resources:
  # SNS Topic для reliability alerts
  ReliabilityAlertsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: flowlogic-${self:provider.stage}-reliability-alerts
      DisplayName: FlowLogic Reliability Alerts
      Subscription:
        - Protocol: email
          Endpoint: devops@flowlogic.shop
      Tags:
        - Key: Environment
          Value: ${self:provider.stage}
        - Key: Purpose
          Value: Reliability and monitoring alerts

  # CloudWatch Alarms для критических метрик
  LambdaErrorsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: flowlogic-${self:provider.stage}-lambda-errors
      AlarmDescription: "P0: Lambda error rate > 10/min"
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref ReliabilityAlertsTopic
      Dimensions:
        - Name: FunctionName
          Value: ${self:service}-${self:provider.stage}-api

  ApiGateway5xxAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: flowlogic-${self:provider.stage}-api-5xx
      AlarmDescription: "P0: API Gateway 5xx errors > 20 in 5 min"
      MetricName: 5XXError
      Namespace: AWS/ApiGateway
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 20
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref ReliabilityAlertsTopic
      Dimensions:
        - Name: ApiName
          Value: ${self:provider.stage}-${self:service}

  DynamoDBThrottlingAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: flowlogic-${self:provider.stage}-dynamodb-throttles
      AlarmDescription: "P0: DynamoDB throttling detected"
      MetricName: UserErrors
      Namespace: AWS/DynamoDB
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref ReliabilityAlertsTopic
      Dimensions:
        - Name: TableName
          Value: ${self:custom.tables.users}

  ApiLatencyP95Alarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: flowlogic-${self:provider.stage}-api-latency-p95
      AlarmDescription: "P1: API P95 latency > 1s"
      MetricName: Duration
      Namespace: AWS/Lambda
      ExtendedStatistic: p95
      Period: 300
      EvaluationPeriods: 2
      Threshold: 1000
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref ReliabilityAlertsTopic
      Dimensions:
        - Name: FunctionName
          Value: ${self:service}-${self:provider.stage}-api

  DLQDepthAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: flowlogic-${self:provider.stage}-dlq-depth
      AlarmDescription: "P0: DLQ has messages (failed Lambda executions)"
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Statistic: Average
      Period: 60
      EvaluationPeriods: 1
      Threshold: 0
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref ReliabilityAlertsTopic
      Dimensions:
        - Name: QueueName
          Value: flowlogic-${self:provider.stage}-processing-dlq

Outputs:
  ReliabilityAlertsTopicArn:
    Description: ARN of SNS topic for reliability alerts
    Value: !Ref ReliabilityAlertsTopic
    Export:
      Name: flowlogic-${self:provider.stage}-reliability-alerts-topic-arn
