Resources:
  # Dead Letter Queue для failed Lambda invocations
  ProcessingDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: flowlogic-${self:provider.stage}-processing-dlq
      MessageRetentionPeriod: 1209600  # 14 days
      VisibilityTimeout: 60  # 1 minute
      ReceiveMessageWaitTimeSeconds: 0  # Short polling
      Tags:
        - Key: Environment
          Value: ${self:provider.stage}
        - Key: Purpose
          Value: Dead Letter Queue for failed Lambda executions
  # DynamoDB Tables
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: flowlogic-${self:provider.stage}-users
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: email
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: email-index
          KeySchema:
            - AttributeName: email
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  SubscriptionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: flowlogic-${self:provider.stage}-subscriptions
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: subscription_id
          AttributeType: S
        - AttributeName: stripe_customer_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: subscription_id
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: stripe-customer-index
          KeySchema:
            - AttributeName: stripe_customer_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  AssessmentsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: flowlogic-${self:provider.stage}-assessments
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: assessment_id
          AttributeType: S
        - AttributeName: test_id
          AttributeType: N
        - AttributeName: month_key
          AttributeType: S
        - AttributeName: created_at
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: assessment_id
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: test-type-index
          KeySchema:
            - AttributeName: test_id
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: month-index
          KeySchema:
            - AttributeName: month_key
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  PlansTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: flowlogic-${self:provider.stage}-plans
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: plan_id
          AttributeType: S
        - AttributeName: is_active
          AttributeType: N
        - AttributeName: created_at
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: plan_id
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: active-index
          KeySchema:
            - AttributeName: is_active
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  CalendarTasksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: flowlogic-${self:provider.stage}-calendar-tasks
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: task_date
          AttributeType: S
        - AttributeName: created_at
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: task_date
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: date-index
          KeySchema:
            - AttributeName: task_date
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  ProgressTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: flowlogic-${self:provider.stage}-progress
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: date
          AttributeType: S
        - AttributeName: streak
          AttributeType: N
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: date
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: streak-index
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: streak
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  UserLimitsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: flowlogic-${self:provider.stage}-user-limits
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  MigrationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: flowlogic-${self:provider.stage}-migrations
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: version
          AttributeType: S
      KeySchema:
        - AttributeName: version
          KeyType: HASH
      # Streams disabled for migrations table
      SSESpecification:
        SSEEnabled: true
        SSEType: KMS
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # S3 Bucket
  VideosBucket:
    Type: AWS::S3::Bucket
    Properties:
      # Удаляем BucketName для обхода ResourceExistenceCheck конфликта имен
      # CloudFormation сгенерирует уникальное имя автоматически
      # TODO: Вернуть фиксированное имя после успешного деплоя
      # BucketName: ${self:custom.s3.bucket}
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: TransitionToGlacier
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: GLACIER
          - Id: DeleteOldVideos
            Status: Enabled
            ExpirationInDays: 90
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
